name = "Paleolithicraft"
author = "Sanguine_Sloth"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bb2c66a879e26b644d7aacf91f92618a5fa796c5ca9aadbcefebf8c01162a8b"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
