name = "Paleolithicraft"
author = "Sanguine_Sloth"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6be1888cbd635b7b238aa5e275d7714ce6945d852158ae65ee51821969ce9c8"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
